# Uses Iceberg JDBC catalog metadata in Postgres for local mode.
connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.file-format=AVRO
iceberg.jdbc-catalog.catalog-name=local_catalog
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://postgres:5432/${ENV:POSTGRES_DB}
iceberg.jdbc-catalog.connection-user=${ENV:ICEBERG_JDBC_USER}
iceberg.jdbc-catalog.connection-password=${ENV:ICEBERG_JDBC_PASSWORD}
iceberg.jdbc-catalog.default-warehouse-dir=file:///opt/flink/local-warehouse
fs.hadoop.enabled=true
